export const MEDICAL_ADVICE = {
  allergy: {
    symptoms: ["allergy", "allergic", "rash", "itch", "sneezing", "runny nose", "watery eyes"],
    advice: {
      en_IN: "You might be experiencing an allergy. Here's what you can do:\n\n1. **Identify the trigger** - Note what you were exposed to before symptoms appeared\n2. **Immediate relief**:\n   • Take antihistamines (Cetirizine, Loratadine, or Fexofenadine)\n   • Apply cool compress to itchy areas\n   • Avoid scratching\n   • Wash affected area with cold water\n3. **Environmental control**:\n   • Keep windows closed during high pollen season\n   • Use air purifiers\n   • Wash clothes and take a shower after outdoor activities\n4. **When to seek help**:\n   • If symptoms worsen or persist beyond 3-4 days\n   • If you develop difficulty breathing (call 108 immediately)\n   • If swelling affects face or throat\n5. **Prevention**:\n   • Avoid known allergens\n   • Use hypoallergenic products\n   • Keep a diary of triggers\n\nWould you like to call a doctor on 108 or notify your guardians?",
      hi_IN: "आप एलर्जी का अनुभव कर रहे हैं। यह करें:\n\n1. **ट्रिगर पहचानें** - लक्षण दिखने से पहले क्या हुआ\n2. **तुरंत राहत**:\n   • एंटीहिस्टामाइन लें\n   • प्रभावित क्षेत्र पर ठंडी पट्टी लगाएं\n   • खुजली न करें\n3. **3-4 दिन बाद भी ठीक न हो तो डॉक्टर को कॉल करें**\n4. **तुरंत 108 कॉल करें यदि सांस लेने में कठिनाई हो**"
    }
  },
  fever: {
    symptoms: ["fever", "high temperature", "body ache", "chills", "feeling hot"],
    advice: {
      en_IN: "You have a fever. Here's what to do:\n\n1. **Immediate measures**:\n   • Rest in a cool room\n   • Take paracetamol (500mg) or ibuprofen (400mg)\n   • Drink plenty of fluids - water, juice, warm tea\n   • Use a cold compress on forehead\n2. **Monitor temperature**:\n   • Check temperature every 2-4 hours\n   • If above 103°F (39.4°C), contact doctor\n3. **Care tips**:\n   • Wear light clothing\n   • Eat light, nutritious food\n   • Avoid strenuous activity\n4. **When to seek help**:\n   • Fever lasts more than 3 days\n   • Temperature exceeds 104°F (40°C)\n   • Severe headache, confusion, or difficulty breathing\n   • Call 108 for medical emergency\n5. **Prevention**:\n   • Maintain hygiene\n   • Avoid close contact with sick people\n   • Boost immunity with fruits, vegetables, vitamin C\n\nWould you like me to call emergency services or notify your guardians?",
      hi_IN: "आपको बुखार है। करें:\n\n1. **तुरंत उपाय**:\n   • ठंडे कमरे में आराम करें\n   • पैरासिटामॉल लें\n   • खूब पानी पिएं\n2. **तापमान मापें**:\n   • 104°F से ऊपर तो डॉक्टर को कॉल करें\n3. **3 दिन से ज्यादा रहे तो 108 पर कॉल करें**"
    }
  },
  headache: {
    symptoms: ["headache", "migraine", "head pain", "throbbing", "pressure in head"],
    advice: {
      en_IN: "You have a headache. Try these remedies:\n\n1. **Quick relief**:\n   • Take aspirin (300mg) or paracetamol (500mg)\n   • Drink water - dehydration is a common cause\n   • Rest in a dark, quiet room\n   • Apply warm/cold compress\n2. **Tension headache tips**:\n   • Massage neck and shoulders\n   • Do gentle stretches\n   • Take slow, deep breaths\n3. **Migraine management**:\n   • Lie down in dark room\n   • Use cold compress on forehead\n   • Take prescribed migraine medication\n   • Avoid bright lights and loud sounds\n4. **Prevention**:\n   • Stay hydrated\n   • Maintain regular sleep schedule\n   • Manage stress\n   • Limit screen time\n5. **When to seek help**:\n   • Headache is severe and sudden\n   • Accompanied by fever, stiff neck, or confusion\n   • Vision changes or weakness\n   • Call 108 for severe cases\n\nWould you like to contact a healthcare professional?",
      hi_IN: "आपको सिरदर्द है। आजमाएं:\n\n1. **तुरंत राहत**:\n   • दवाई लें (पैरासिटामॉल)\n   • पानी पिएं\n   • अंधेरे कमरे में आराम करें\n2. **थोड़ा दबाव या तनाव है तो**:\n   • गर्दन और कंधे की मालिश करें\n3. **3-4 घंटे बाद ठीक न हो तो डॉक्टर को बुलाएं**"
    }
  },
  breathing_issue: {
    symptoms: ["breathing", "shortness of breath", "asthma", "chest tight", "difficult breathing", "wheezing"],
    advice: {
      en_IN: "**BREATHING DIFFICULTY - URGENT**\n\n⚠️ If you're having severe difficulty breathing, CALL 108 IMMEDIATELY\n\n**Quick steps**:\n1. **Sit upright** - Straight back, relaxed shoulders\n2. **Breathe slowly** - In through nose (4 count), out through mouth (4 count)\n3. **Use inhaler** - If you have asthma medication, use it now\n4. **Remove tight clothing** - Loosen anything restricting your chest\n5. **Find fresh air** - Move to a well-ventilated area\n\n**When to call 108**:\n• Severe shortness of breath\n• Chest pain\n• Lips or fingernails turning blue\n• Confusion or difficulty speaking\n• Persistent wheezing\n\n**Asthma management**:\n• Keep rescue inhaler handy\n• Avoid allergens\n• Do breathing exercises daily\n• Maintain peak flow meter readings\n\n**This is a serious condition. Please seek immediate medical attention.**",
      hi_IN: "**सांस लेने में कठिनाई - तुरंत 108 कॉल करें!**\n\nयदि गंभीर कठिनाई है:\n1. सीधे बैठें\n2. धीरे-धीरे सांस लें\n3. इनहेलर का उपयोग करें (यदि है)\n4. तंग कपड़े हटाएं\n5. ताजी हवा लें\n\n**तुरंत 108 कॉल करें!**"
    }
  },
  cold: {
    symptoms: ["cold", "cough", "sore throat", "congestion", "runny nose"],
    advice: {
      en_IN: "You have a cold. Here's your recovery plan:\n\n1. **Rest and recovery**:\n   • Get 7-9 hours of sleep\n   • Avoid strenuous activities\n   • Stay home for 24-48 hours\n2. **Hydration**:\n   • Drink warm liquids - tea, soup, warm water\n   • Add honey and lemon to water\n   • Avoid caffeine and alcohol\n3. **Symptom management**:\n   • For sore throat: gargle with salt water\n   • For congestion: use saline nasal drops\n   • For cough: honey spoon or cough syrup\n4. **Nutrition**:\n   • Vitamin C: oranges, kiwi, strawberries\n   • Zinc: pumpkin seeds, almonds\n   • Protein: eggs, chicken, yogurt\n5. **Prevention for others**:\n   • Wash hands frequently\n   • Cover cough/sneeze\n   • Use separate utensils\n6. **When to see doctor**:\n   • Symptoms worsen after 5 days\n   • High fever (>101°F)\n   • Difficulty breathing\n\nMost colds resolve in 7-10 days. Drink lots of fluids!",
      hi_IN: "आपको सर्दी है। करें:\n\n1. **आराम करें** - 7-9 घंटे सोएं\n2. **गुनगुना पानी पिएं** - शहद और नींबू के साथ\n3. **खांसी के लिए** - शहद का चम्मच या दवाई\n4. **गले के लिए** - नमक के पानी से गरारे करें\n5. **फल खाएं** - सेब, संतरा, कीवी\n6. **5-7 दिन में ठीक होना चाहिए**"
    }
  },
  diarrhea: {
    symptoms: ["diarrhea", "loose stool", "stomach pain", "food poisoning", "vomiting"],
    advice: {
      en_IN: "You have diarrhea. Here's what to do:\n\n1. **Stay hydrated** (MOST IMPORTANT):\n   • ORS (Oral Rehydration Solution) - 1 packet per liter of water\n   • Coconut water\n   • Buttermilk\n   • Rice water\n   • Avoid milk, coffee, alcohol\n2. **Rest your stomach**:\n   • Start with light foods after 2 hours\n   • Bananas, rice, applesauce, toast (BRAT diet)\n   • Avoid fatty, spicy foods\n3. **Medications**:\n   • Loperamide (if needed) - Ask pharmacist\n   • Probiotics - Helps restore gut bacteria\n4. **Hygiene**:\n   • Wash hands frequently\n   • Separate from others\n   • Use different bathroom if possible\n5. **When to seek help**:\n   • Diarrhea lasts more than 3-4 days\n   • Blood in stool\n   • Severe abdominal pain\n   • Signs of severe dehydration\n   • Call 108 for emergencies\n\n**Focus on hydration - drink more than normal!**",
      hi_IN: "आपको दस्त है। करें:\n\n1. **पानी पिएं** (सबसे जरूरी):\n   • ORS घोल\n   • नारियल पानी\n   • छाछ\n2. **हल्का खाना खाएं**:\n   • केला, चावल, टोस्ट\n   • तेल-मसाले वाला खाना न खाएं\n3. **3-4 दिन बाद भी ठीक न हो तो डॉक्टर को कॉल करें**"
    }
  },
  scratch: {
    symptoms: ["scratch", "cut", "wound", "scrape"],
    advice: {
      en_IN: "First Aid for Scratch/Cut:\n\n1. **Stop bleeding**:\n   • Apply gentle pressure with clean cloth for 5-10 minutes\n   • Elevate the injured area\n2. **Clean the wound**:\n   • Rinse with clean running water\n   • Gently wash with soap and water\n   • Pat dry with clean cloth\n3. **Disinfect**:\n   • Apply antiseptic (Dettol, Savlon)\n   • Use antibiotic ointment if available\n4. **Cover if needed**:\n   • Bandage to keep clean and protected\n   • Change bandage daily\n5. **Monitor**:\n   • Watch for signs of infection (increased redness, swelling, pus, heat)\n   • If infected, call doctor\n6. **When to seek help**:\n   • Deep cut (won't stop bleeding)\n   • Signs of infection\n   • If you can see fat or muscle beneath\n\nMost scratches heal within 1-2 weeks!",
      hi_IN: "खरोंच/कट के लिए प्राथमिक चिकित्सा:\n\n1. **खून बंद करें**:\n   • साफ कपड़े से 5-10 मिनट दबाएं\n   • घायल हिस्से को ऊपर उठाएं\n2. **घाव साफ करें**:\n   • साफ पानी से धोएं\n   • साबुन से धीरे से साफ करें\n3. **कीटाणुनाशक लगाएं**:\n   • डेटॉल या सेवलॉन लगाएं\n4. **पट्टी बांधें**:\n   • साफ रखने के लिए पट्टी बांधें\n   • रोज बदलें\n5. **संक्रमण के संकेत देखें**:\n   • सूजन, पस, लालिमा\n   • अगर संक्रमण हो तो डॉक्टर को कॉल करें"
    }
  },
  snake_bite: {
    symptoms: ["snake", "bite", "venom", "fang marks"],
    advice: {
      en_IN: "**SNAKE BITE - URGENT ACTION REQUIRED**\n\n🐍 **CALL 108 IMMEDIATELY!**\n\n**First Aid (While waiting for ambulance)**:\n1. **Stay calm** - Keep the person still\n2. **Remove constricting items**:\n   • Take off rings, bracelets, watch\n   • These can cut off circulation as swelling occurs\n3. **Immobilize the limb**:\n   • Keep the bitten limb completely still\n   • Use sling or gentle splint\n   • Don't move unnecessary\n4. **Position for blood flow**:\n   • Keep bite site below heart level\n   • Lie down flat if possible\n5. **Apply pressure immobilization**:\n   • Wrap bandage firmly (like ACE wrap) from bite site upward\n   • Should be firm but not cutting off circulation\n6. **DO NOT**:\n   • Apply ice or heat\n   • Apply tourniquets\n   • Cut or suck the bite\n   • Use traditional remedies\n   • Apply electric shock\n7. **Mark swelling**:\n   • Use pen to mark swelling edge every 15 minutes\n   • Show doctor the progression\n\n**Get to hospital ASAP - Antivenom may be needed!**",
      hi_IN: "**सांप के काटने पर - तुरंत 108 कॉल करें!**\n\n1. **शांत रहें** - व्यक्ति को स्थिर रखें\n2. **कसी चीजें निकालें** - अंगूठी, कंगन\n3. **काटे हुए हिस्से को हिलाएं नहीं**\n4. **पट्टी बांधें** - काटे से ऊपर की तरफ\n5. **यह न करें**:\n   • बर्फ न लगाएं\n   • टूर्निकेट न बांधें\n   • घाव को काटें-चूसें नहीं\n6. **तुरंत अस्पताल जाएं**\n\n**एंटीवेनम की जरूरत हो सकती है!**"
    }
  },
  choking: {
    symptoms: ["choking", "can't breathe", "blocked airway", "food stuck"],
    advice: {
      en_IN: "**CHOKING - LIFE-THREATENING EMERGENCY**\n\n⚠️ **CALL 112 IMMEDIATELY IF UNABLE TO HELP IN 1 MINUTE**\n\n**For Conscious Adult - Heimlich Maneuver**:\n1. **Stand behind the person**\n2. **Place fist** above navel, below ribcage\n3. **Grasp fist** with other hand\n4. **Quick upward thrusts**:\n   • Push hard into abdomen\n   • Repeat 5 times\n5. **Alternate with back blows**:\n   • Stand to side\n   • Give 5 firm back blows between shoulder blades\n6. **Repeat** until object dislodges or person becomes unconscious\n\n**For Infant/Small Child**:\n1. Hold face down on your forearm\n2. Give 5 back blows between shoulders\n3. Turn face up, supporting head\n4. Give 5 chest thrusts with 2 fingers\n5. Repeat until object comes out\n\n**If unconscious**:\n1. Start CPR immediately\n2. Call 112\n3. Attempt to dislodge object when checking airway\n\n**Prevention**:\n• Chew food well\n• Don't talk with full mouth\n• Supervise children while eating",
      hi_IN: "**गले में अटकना - जीवन की खतरे में स्थिति**\n\n🆘 **तुरंत 112 कॉल करें!**\n\n**होमलिच हैंडलिंग (Heimlich Maneuver)**:\n1. **व्यक्ति के पीछे खड़े हों**\n2. **मुट्ठी** नाभि से ऊपर रखें\n3. **तेज अपवार्ड थ्रस्ट**:\n   • पेट में जोर से दबाएं\n   • 5 बार दोहराएं\n4. **पीठ पर वार** भी करें\n5. **तब तक दोहराएं जब तक वस्तु न निकल जाए**\n\n**यदि बेहोश हो**:\n• तुरंत CPR शुरू करें\n• 112 कॉल करें"
    }
  },
  bruise: {
    symptoms: ["bruise", "bruised", "black and blue", "contusion"],
    advice: {
      en_IN: "First Aid for Bruises:\n\n1. **Immediate (First 48 hours) - RICE**:\n   • **R - Rest**: Stop activity immediately\n   • **I - Ice**: Apply ice pack for 15-20 minutes, 4-6 times daily\n   • **C - Compression**: Wrap with elastic bandage (not too tight)\n   • **E - Elevation**: Keep bruised area above heart level\n2. **Pain relief**:\n   • Paracetamol (500mg) or Ibuprofen (400mg)\n   • Avoid aspirin (increases bleeding)\n3. **After 48 hours**:\n   • Gentle heat application\n   • Massage around (not directly on) bruise\n   • Gradually increase activity\n4. **Healing**:\n   • Bruises typically fade in 1-3 weeks\n   • Color changes from purple → green → yellow\n5. **When to see doctor**:\n   • Severe swelling\n   • Inability to move limb\n   • Bruise from falls or impacts\n   • Unexplained bruises appearing frequently\n\n**Bruises usually heal on their own!**",
      hi_IN: "चोट के निशान के लिए प्राथमिक चिकित्सा:\n\n1. **तुरंत (पहले 48 घंटे)**:\n   • आराम करें\n   • बर्फ लगाएं 15-20 मिनट, दिन में 4-6 बार\n   • कसकर पट्टी बांधें\n   • हिस्से को ऊपर उठाएं\n2. **दर्द राहत**:\n   • पैरासिटामॉल लें\n3. **48 घंटे के बाद**:\n   • गुनगुनी गर्मी लगाएं\n   • धीरे-धीरे मालिश करें\n4. **चोट 1-3 सप्ताह में ठीक हो जाती है**"
    }
  },
  burn: {
    symptoms: ["burn", "burnt", "burned", "scald", "fire"],
    advice: {
      en_IN: "First Aid for Burns:\n\n**Degree Classification**:\n• 1st Degree: Red, painful, no blistering\n• 2nd Degree: Blistering, severe pain\n• 3rd Degree: White/charred, deep tissue damage\n\n**Immediate Action**:\n1. **Cool the burn** (First 20 minutes):\n   • Run cool (not cold) water for 10-20 minutes\n   • DO NOT use ice directly\n   • DO NOT apply oil or butter\n2. **Remove constrictive items**:\n   • Remove jewelry, tight clothing\n   • Don't remove stuck fabric\n3. **Cover the burn**:\n   • Use clean, dry cloth\n   • Loose bandage (not tight)\n4. **Pain management**:\n   • Paracetamol or Ibuprofen\n5. **Prevention of infection**:\n   • Apply antibiotic ointment\n   • Change bandage daily\n\n**When to seek medical help**:\n• Area larger than 3 inches (7.5cm)\n• On face, hands, feet, genitals, joints\n• 2nd or 3rd degree burns\n• Caused by chemicals or electricity\n• CALL 108 FOR SEVERE BURNS\n\n**DO NOT**:\n• Apply ice directly\n• Use butter, oil, or home remedies\n• Pop blisters\n• Apply adhesive bandages",
      hi_IN: "जलने के लिए प्राथमिक चिकित्सा:\n\n**तुरंत करें**:\n1. **ठंडा पानी डालें** (20 मिनट)\n   • ठंडा पानी चलाएं (बर्फ नहीं)\n   • तेल/घी न लगाएं\n2. **कसी चीजें निकालें** - अंगूठी, कपड़े\n3. **साफ कपड़े से ढकें**\n4. **दर्द की दवा लें**\n5. **संक्रमण रोकने के लिए**:\n   • एंटीबायोटिक मरहम लगाएं\n\n**डॉक्टर के पास कब जाएं**:\n• बड़ा क्षेत्र\n• चेहरा, हाथ, पैर\n• गहरा जलना\n\n**यह न करें**:\n• बर्फ न लगाएं\n• तेल/घी न लगाएं\n• छाले न फोड़ें"
    }
  },
  splinter: {
    symptoms: ["splinter", "thorn", "stuck", "penetrated"],
    advice: {
      en_IN: "Removing a Splinter:\n\n1. **Prepare**:\n   • Wash hands with soap\n   • Disinfect tweezers with alcohol\n   • Clean area around splinter\n2. **Remove splinter**:\n   • Use magnifying glass if needed\n   • Grab as close to skin as possible\n   • Pull straight out in direction of splinter\n   • Don't push deeper\n3. **If stuck deep**:\n   • Soak in warm water for 10 minutes\n   • Apply Epsom salt solution\n   • Try again after soaking\n4. **After removal**:\n   • Squeeze gently to remove any debris\n   • Wash with soap and water\n   • Apply antiseptic\n5. **Prevent infection**:\n   • Keep area clean\n   • Watch for redness or swelling\n6. **When to see doctor**:\n   • Can't remove splinter\n   • Signs of infection\n   • Splinter in eye or deep in skin\n\n**Most splinters come out easily!**",
      hi_IN: "कांटा/तिनका निकालना:\n\n1. **तैयारी करें**:\n   • हाथ धोएं\n   • संदंश को अल्कोहल से साफ करें\n2. **निकालें**:\n   • जितना संभव हो त्वचा के पास पकड़ें\n   • सीधे खींचें\n   • गहरा न दबाएं\n3. **अगर गहरा है**:\n   • गुनगुने पानी में 10 मिनट भिगोएं\n   • Epsom नमक लगाएं\n4. **निकालने के बाद**:\n   • धीरे दबाएं\n   • साफ पानी से धोएं\n   • कीटाणुनाशक लगाएं\n5. **डॉक्टर के पास कब जाएं**:\n   • निकल न सके\n   • संक्रमण के संकेत"
    }
  },
  fainting: {
    symptoms: ["fainting", "faint", "passed out", "syncope", "loss of consciousness"],
    advice: {
      en_IN: "**FAINTING - EMERGENCY FIRST AID**\n\n**If someone is fainting**:\n1. **Lay them down** immediately\n2. **Raise legs** 12 inches above heart\n3. **Turn head to side** to prevent choking\n4. **Check for breathing** and pulse\n5. **Loosen tight clothing** - belt, collar, tie\n6. **Cool the face** - splash cool water gently\n\n**Recovery position** (if unconscious):\n• On side with one leg bent\n• Head tilted back to open airway\n• Can turn to side for drainage\n\n**When they regain consciousness**:\n• Keep lying down for 10-15 minutes\n• Don't let them sit/stand abruptly\n• Offer water slowly when alert\n• Have them rest for 1-2 hours\n\n**When to call 108**:\n• Person doesn't regain consciousness within 1-2 minutes\n• Multiple fainting episodes\n• Chest pain, difficulty breathing\n• Head injury from fall\n• Diabetic (check blood sugar)\n• Pregnant women fainting\n\n**Common causes**:\n• Low blood pressure\n• Dehydration\n• Blood sugar drop\n• Anxiety\n• Sudden pain\n\n**Prevention**:\n• Stay hydrated\n• Eat regular meals\n• Avoid sudden movements\n• Don't stand too quickly",
      hi_IN: "**बेहोशी - आपातकालीन प्राथमिक चिकित्सा**\n\n1. **तुरंत लिटा दें**\n2. **पैर 12 इंच ऊपर उठाएं**\n3. **सिर को बगल में करें** - जीभ न गले में आए\n4. **सांस/नाड़ी देखें**\n5. **कसे कपड़े ढीले करें**\n6. **ठंडा पानी छिड़कें**\n\n**होश आने पर**:\n• 10-15 मिनट लिटे रहें\n• तुरंत न उठें\n• पानी पिएं\n• आराम करें\n\n**108 कॉल करें अगर**:\n• 1-2 मिनट में होश न आए\n• बार-बार बेहोशी\n• सीने में दर्द\n• गिरने से चोट"
    }
  },
  low_blood_pressure: {
    symptoms: ["low blood pressure", "hypotension", "dizzy", "lightheaded", "weak"],
    advice: {
      en_IN: "Managing Low Blood Pressure:\n\n**Immediate Relief**:\n1. **Sit or lie down** immediately\n2. **Raise legs** above heart level\n3. **Drink water** - Dehydration is common cause\n4. **Eat salty snack** - Salt helps retain water\n5. **Apply pressure** to legs - Compress muscles\n\n**Ongoing Management**:\n1. **Increase fluid intake**:\n   • Drink 2-3 liters water daily\n   • Electrolyte drinks (coconut water)\n   • Avoid excessive caffeine\n2. **Dietary changes**:\n   • Increase salt (if advised by doctor)\n   • Eat small, frequent meals\n   • Include complex carbs and protein\n   • Eat beets, carrots, leafy greens\n3. **Lifestyle modifications**:\n   • Rise slowly from bed (especially morning)\n   • Avoid sudden position changes\n   • Wear compression stockings\n   • Regular moderate exercise\n4. **When to see doctor**:\n   • Persistent dizziness\n   • Fainting spells\n   • Shortness of breath\n   • Chest pain\n5. **Medication**:\n   • Doctor may prescribe if lifestyle changes don't help\n\n**Call 108 if**:\n   • Severe dizziness with confusion\n   • Chest pain\n   • Difficulty breathing\n   • Loss of consciousness",
      hi_IN: "कम रक्तचाप का प्रबंधन:\n\n**तुरंत राहत**:\n1. **बैठ जाएं या लेट जाएं**\n2. **पैर ऊपर उठाएं**\n3. **पानी पिएं**\n4. **नमकीन खाना खाएं**\n5. **पैरों पर दबाव डालें**\n\n**दीर्घकालीन प्रबंधन**:\n1. **पानी बढ़ाएं** - 2-3 लीटर प्रतिदिन\n2. **नमक बढ़ाएं** (डॉक्टर के सलाह से)\n3. **छोटे, बार-बार खाना खाएं**\n4. **धीरे से उठें**\n5. **व्यायाम करें**\n\n**108 कॉल करें अगर**:\n• गंभीर चक्कर\n• बेहोशी\n• सांस की कमी"
    }
  },
  heart_attack: {
    symptoms: ["heart attack", "chest pain", "cardiac", "myocardial"],
    advice: {
      en_IN: "**HEART ATTACK - LIFE-THREATENING EMERGENCY**\n\n🆘 **CALL 112 IMMEDIATELY!**\n\n**Symptoms of Heart Attack**:\n• Chest pain (pressure, tightness, squeezing)\n• Pain spreading to arm, neck, jaw\n• Shortness of breath\n• Cold sweats\n• Nausea\n• Weakness\n• Anxiety or sense of doom\n\n**IMMEDIATE FIRST AID**:\n1. **CALL 112 FIRST** - Don't delay!\n2. **Stop all activity** - Sit or lie down\n3. **Chew aspirin** (if not allergic):\n   • 300mg aspirin OR\n   • 5-7 tablets of 75mg aspirin\n   • Chew it (faster absorption)\n4. **Loosen clothing** - Remove tight items\n5. **Open airway** - Tilt head back slightly\n6. **If prescribed**:\n   • Take nitroglycerin tablet under tongue\n   • Repeat every 5 minutes (up to 3 doses)\n7. **Monitor breathing** - Be ready for CPR\n8. **Stay calm** - Keep person calm and reassured\n9. **Note time** - When symptoms started\n\n**While waiting for ambulance**:\n• Keep person sitting/lying down\n• Don't let them move around\n• Have family/friends present\n• Arrange access for paramedics\n\n**CPR - If becomes unresponsive**:\n• Start chest compressions immediately\n• 100-120 compressions per minute\n• Push hard and fast on chest\n• Continue until ambulance arrives\n\n**DO NOT**:\n• Make them walk around\n• Give them food\n• Delay calling 112\n• Leave them alone",
      hi_IN: "**दिल का दौरा - जीवन रक्षक आपातकाल**\n\n🆘 **तुरंत 112 कॉल करें!**\n\n**लक्षण**:\n• सीने में दर्द\n• दर्द बाहु, गर्दन, जबड़े में\n• सांस की कमी\n• ठंडा पसीना\n• मतली\n\n**तुरंत करें**:\n1. **112 कॉल करें** - देरी न करें!\n2. **रुकें - बैठ/लेट जाएं**\n3. **एस्पिरिन चबाएं** (अगर एलर्जी न हो)\n4. **कसे कपड़े ढीले करें**\n5. **अगर नाइट्रोग्लिसरीन है** - जीभ के नीचे रखें\n6. **शांत रहें**\n7. **एम्बुलेंस की प्रतीक्षा करें**\n\n**बेहोश हो तो CPR दें**:\n• छाती पर दबाव 100-120 बार/मिनट\n• तेजी से जोर से दबाएं\n• एम्बुलेंस आने तक जारी रखें"
    }
  },
  pregnant_help: {
    symptoms: ["pregnant", "pregnancy", "expectant mother", "labour", "labor", "contraction"],
    advice: {
      en_IN: "Support for Pregnant Women:\n\n**During Pregnancy**:\n1. **Regular checkups**:\n   • Monthly until 6 months\n   • Bi-weekly from 6-8 months\n   • Weekly after 8 months\n2. **Nutrition**:\n   • Eat iron-rich foods (spinach, meat)\n   • Calcium (milk, yogurt)\n   • Folic acid (green vegetables)\n   • Protein (eggs, legumes)\n3. **Exercise**:\n   • Prenatal yoga\n   • Walking (30 minutes daily)\n   • Pelvic floor exercises\n4. **Rest**:\n   • 8-10 hours sleep\n   • Avoid standing for long periods\n   • Elevate feet when sitting\n\n**Labour Pain Management**:\n1. **Breathing techniques**:\n   • Deep breathing during contractions\n   • Slow, rhythmic breathing\n2. **Positions**:\n   • Walk around\n   • Squat or sit on birthing ball\n   • Rock back and forth\n3. **Pain relief**:\n   • Massage by partner\n   • Warm shower/bath\n   • Medication options (discuss with doctor)\n\n**Emergency Symptoms - CALL 108**:\n• Bleeding (more than spotting)\n• Severe abdominal pain\n• Sudden dizziness/fainting\n• Difficulty breathing\n• Loss of consciousness\n• Severe headache with vision changes\n• Water breaks but no contractions in 12 hours\n\n**When to go to hospital**:\n• Contractions every 3-5 minutes\n• Contractions lasting 60-90 seconds\n• Water breaks\n• Vaginal bleeding\n• Severe pain\n\n**For Birth Partner**:\n• Be calm and supportive\n• Provide comfort measures\n• Keep hydrated\n• Update family members\n• Be ready to assist medical team",
      hi_IN: "गर्भवती महिलाओं के लिए सहायता:\n\n**गर्भावस्था के दौरान**:\n1. **नियमित जांच** - डॉक्टर से मिलें\n2. **पोषण**:\n   • लोहे वाला खाना (पालक, मांस)\n   • कैल्शियम (दूध, दही)\n   • प्रोटीन (अंडे, दालें)\n3. **व्यायाम**:\n   • योग\n   • 30 मिनट टहलें\n4. **आराम** - 8-10 घंटे नींद\n\n**प्रसव पीड़ा का प्रबंधन**:\n1. **सांस लेने की तकनीक** - गहरी सांस लें\n2. **मुद्राएं** - बदलते रहें\n3. **मालिश** - साथी करे\n\n**108 कॉल करें अगर**:\n• खून बहना\n• गंभीर पेट दर्द\n• बेहोशी\n• सांस की कमी\n\n**अस्पताल कब जाएं**:\n• संकुचन हर 3-5 मिनट\n• पानी टूटना\n• खून बहना"
    }
  },
  menstruation: {
    symptoms: ["period", "menstruation", "periods", "cramps", "period cramps", "menses", "menstrual"],
    advice: {
      en_IN: "**Menstruation - Period Advice & Management**\n\n**Normal Period Information**:\n• Average cycle: 21-35 days\n• Flow lasts: 3-7 days\n• Normal flow: 30-40ml per day\n• First periods may be irregular (normal!)\n\n**Managing Period Cramps**:\n1. **Heat therapy** (most effective!):\n   • Hot water bottle on lower abdomen\n   • Heating pad for 15-20 minutes\n   • Warm shower or bath\n2. **Exercise**:\n   • Light walking\n   • Gentle yoga\n   • Stretching\n   • Helps release endorphins\n3. **Medication**:\n   • Ibuprofen (400mg) - Most effective\n   • Paracetamol (500mg)\n   • Take at first sign of cramps\n4. **Dietary support**:\n   • Increase calcium: milk, yogurt, cheese\n   • Magnesium: dark chocolate, nuts, seeds\n   • Iron: meat, beans, spinach\n   • Stay hydrated: drink 8-10 glasses water\n5. **Rest**:\n   • Get enough sleep\n   • Reduce stress\n   • Light activity preferred over bed rest\n\n**Heavy Periods - When to Seek Help**:\n🚨 Call doctor if:\n• Soaking through 1+ pads/tampons per hour for several hours\n• Bleeding lasting >7 days\n• Large clots (bigger than a coin)\n• Severe anemia symptoms (weakness, dizziness, shortness of breath)\n• Interfering with daily life\n\n**Irregular Periods**:\n• First 1-3 years: Often irregular (NORMAL)\n• Causes: Stress, diet changes, exercise, weight changes\n• Usually settles down after age 20\n• Track periods: helps doctor diagnose issues\n\n**Hygiene Tips**:\n1. **Use proper products**:\n   • Pads: change every 4-6 hours\n   • Tampons: change every 4-8 hours\n   • Menstrual cups: empty every 12 hours\n2. **Maintain hygiene**:\n   • Wash hands before & after changing\n   • Wash vulva gently with water\n   • Change clothes/bed sheets regularly\n   • Never flush pads/tampons (environmental risk)\n3. **Prevention**:\n   • Don't douche (kills good bacteria)\n   • Avoid strong soaps (use water)\n   • Wear breathable underwear\n\n**Foods that help**:\n✅ Dark leafy greens (iron)\n✅ Nuts & seeds (magnesium)\n✅ Fatty fish (omega-3)\n✅ Dark chocolate (mood + magnesium)\n✅ Ginger tea (reduces inflammation)\n❌ Avoid: Excessive caffeine, salt, sugar\n\n**Emotional Support**:\n• PMS/period mood changes are NORMAL\n• Hormones affect neurotransmitters\n• Exercise & sunlight help mood\n• Talk to someone if feelings are severe\n\n**What's NOT normal - See doctor**:\n• Missed period for 2+ months\n• Severe pain (can't function)\n• Excessive bleeding\n• Foul-smelling discharge\n• Fever with heavy bleeding\n\n**Tracking your cycle**:\n• Use calendar app or notebook\n• Track: start date, end date, symptoms\n• Helps identify patterns\n• Useful for doctor visits\n\n✅ **Remember: Periods are normal and healthy!** Manage discomfort and live your life normally.",
      hi_IN: "**मासिक धर्म - अवधि सलाह और प्रबंधन**\n\n**सामान्य अवधि जानकारी**:\n• औसत चक्र: 21-35 दिन\n• प्रवाह: 3-7 दिन\n• सामान्य प्रवाह: 30-40ml प्रति दिन\n\n**अवधि में ऐंठन प्रबंधन**:\n1. **गर्मी चिकित्सा** (सबसे प्रभावी!):\n   • गर्म पानी की बोतल पेट पर\n   • हीटिंग पैड 15-20 मिनट\n   • गर्म स्नान\n2. **व्यायाम**:\n   • हल्की पैदल यात्रा\n   • कोमल योग\n   • स्ट्रेचिंग\n3. **दवा**:\n   • इबुप्रोफेन (400mg) - सबसे प्रभावी\n   • पैरासिटामॉल (500mg)\n4. **आहार**:\n   • कैल्शियम: दूध, दही, चीज\n   • मैग्नीशियम: डार्क चॉकलेट, नट्स\n   • आयरन: मांस, बीन्स, पालक\n   • खूब पानी पिएं\n5. **आराम**:\n   • पर्याप्त नींद लें\n   • तनाव कम करें\n\n**भारी अवधि - डॉक्टर से कब मिलें**:\n🚨 कॉल करें अगर:\n• घंटे में 1+ पैड/टैम्पन भिगोना\n• 7 दिन से ज्यादा खून\n• बड़े थक्के (सिक्के से बड़े)\n• गंभीर कमजोरी, चक्कर\n\n**अनियमित अवधि**:\n• पहले 1-3 साल: अक्सर अनियमित (सामान्य)\n• कारण: तनाव, आहार, व्यायाम\n• आमतौर पर 20 साल बाद स्थिर हो जाता है\n\n**स्वच्छता सुझाव**:\n1. **उचित उत्पाद**:\n   • पैड: हर 4-6 घंटे बदलें\n   • टैम्पन: हर 4-8 घंटे बदलें\n2. **स्वच्छता बनाए रखें**:\n   • बदलने से पहले/बाद में हाथ धोएं\n   • पानी से धीरे धोएं\n   • नियमित रूप से कपड़े/चादरें बदलें\n\n**मदद करने वाले खाद्य पदार्थ**:\n✅ गहरे पत्तेदार साग (आयरन)\n✅ नट्स (मैग्नीशियम)\n✅ डार्क चॉकलेट (मनोदशा)\n✅ अदरक की चाय (सूजन कम करता है)\n\n**सामान्य नहीं है - डॉक्टर से मिलें**:\n• 2+ महीने अवधि न आना\n• गंभीर दर्द\n• अत्यधिक खून\n• दुर्गंध\n\n✅ **याद रखें: अवधि सामान्य और स्वस्थ है!**"
    }
  },
  nosebleed: {
    symptoms: ["nosebleed", "nosebleeding", "bloody nose", "epistaxis"],
    advice: {
      en_IN: "Controlling a Nosebleed:\n\n1. **Immediate action**:\n   • Sit upright (don't lie back)\n   • Lean forward slightly\n   • Don't tilt head back\n2. **Apply pressure**:\n   • Pinch nose firmly (just below bridge)\n   • Hold for 10-15 minutes continuously\n   • Don't release to check\n   • Use clean cloth or tissue\n3. **Keep cool**:\n   • Apply ice pack to bridge of nose\n   • Or cold compress to cheeks\n   • This constricts blood vessels\n4. **Breathe through mouth** - Don't sniff\n5. **After 10-15 minutes**:\n   • Gently release pressure\n   • If still bleeding, repeat for another 10 minutes\n6. **Once stopped**:\n   • Don't blow nose forcefully for 24 hours\n   • Avoid hot drinks\n   • Keep head elevated\n   • Don't pick or scratch nose\n\n**Prevention**:\n• Use saline nasal drops\n• Humidify air in dry months\n• Avoid picking nose\n• Avoid forceful sneezing\n• Keep nasal passages moist\n\n**When to see doctor**:\n• Bleeding lasts more than 30 minutes\n• Frequent nosebleeds\n• Bleeding after head injury\n• Accompanied by other symptoms\n• Heavy bleeding\n\nMost nosebleeds stop on their own!",
      hi_IN: "नकसीर को नियंत्रित करना:\n\n1. **तुरंत**:\n   • सीधे बैठें (पीछे न झुकें)\n   • आगे की ओर झुकें\n2. **दबाव डालें**:\n   • नाक को मजबूती से दबाएं (पुल के नीचे)\n   • 10-15 मिनट लगातार दबाएं\n   • चेक करने के लिए न छोड़ें\n3. **ठंडा करें**:\n   • बर्फ नाक के पुल पर लगाएं\n4. **मुंह से सांस लें** - नाक से नहीं\n5. **15 मिनट के बाद**:\n   • धीरे से दबाव हटाएं\n   • अगर खून जारी है, दोहराएं\n6. **रुकने के बाद**:\n   • 24 घंटे नाक न उड़ाएं\n   • गर्म पेय न लें\n   • सिर ऊपर रखें\n\n**रोकथाम**:\n• नमक की बूंदें डालें\n• नाक को नम रखें\n\n**डॉक्टर के पास कब जाएं**:\n• 30 मिनट बाद भी खून\n• बार-बार होना\n• बहुत खून बहना"
    }
  },
  sprain: {
    symptoms: ["sprain", "strain", "twisted", "ankle", "wrist", "ligament"],
    advice: {
      en_IN: "First Aid for Sprains & Strains:\n\n**Immediate Treatment - RICE**:\n1. **R - Rest** (First 24-48 hours):\n   • Stop activity immediately\n   • Avoid weight-bearing if leg involved\n   • Use crutches if needed\n2. **I - Ice**:\n   • Apply ice pack for 15-20 minutes\n   • Every 2-3 hours for first 48 hours\n   • Reduces swelling and pain\n3. **C - Compression**:\n   • Wrap with elastic bandage\n   • Firm but not cutting off circulation\n   • Keep on for 48-72 hours\n4. **E - Elevation**:\n   • Keep injured area above heart\n   • Helps reduce swelling\n   • Sleep with pillow supporting limb\n\n**Pain Management**:\n• Paracetamol or Ibuprofen\n• Apply pain relief gel\n\n**After 48-72 hours**:\n• Start gentle movement\n• Gradual increase in activity\n• Apply heat instead of ice\n• Massage around (not on) injury\n\n**Physical Therapy**:\n• Specific exercises for that joint\n• Improves strength and flexibility\n• Prevents re-injury\n\n**When to see doctor**:\n• Severe swelling that increases\n• Unable to move joint\n• Severe pain that won't subside\n• Possible fracture (can't bear weight)\n• Swelling doesn't improve after 3 days\n\n**Recovery time**:\n• Mild: 2-3 weeks\n• Moderate: 4-6 weeks\n• Severe: 8-12 weeks",
      hi_IN: "मोच और तनाव के लिए प्राथमिक चिकित्सा:\n\n**तुरंत - RICE**:\n1. **आराम** (पहले 24-48 घंटे)\n2. **बर्फ** - 15-20 मिनट, 2-3 घंटे में\n3. **पट्टी बांधें** - मजबूत लेकिन कसी न हो\n4. **ऊपर उठाएं** - दिल से ऊपर\n\n**दर्द राहत**:\n• पैरासिटामॉल/इबुप्रोफेन\n\n**48-72 घंटे के बाद**:\n• धीरे-धीरे हिलाएं\n• गुनगुनी गर्मी लगाएं\n• मालिश करें\n\n**डॉक्टर के पास कब जाएं**:\n• गंभीर सूजन\n• हिलाने में असमर्थ\n• गंभीर दर्द\n\n**ठीक होने का समय**:\n• हल्का: 2-3 हफ्ते\n• मध्यम: 4-6 हफ्ते\n• गंभीर: 8-12 हफ्ते"
    }
  },
  insect_bite: {
    symptoms: ["insect bite", "mosquito bite", "bee sting", "wasp", "ant bite"],
    advice: {
      en_IN: "Managing Insect Bites & Stings:\n\n**Immediate First Aid**:\n1. **Remove stinger** (if bee sting):\n   • Scrape with flat edge (card, knife)\n   • Don't squeeze (releases venom)\n   • Remove quickly\n2. **Clean the area**:\n   • Wash with soap and water\n   • Use antiseptic\n3. **Apply ice**:\n   • Ice pack for 10-15 minutes\n   • Reduces swelling and itching\n4. **Reduce itching**:\n   • Apply hydrocortisone cream\n   • Antihistamine tablet\n   • Calamine lotion\n   • Cold compress\n5. **Don't scratch**:\n   • Scratching causes infection\n   • Keep nails trimmed\n   • Wear gloves if sleeping\n\n**Pain & Swelling**:\n• Paracetamol or Ibuprofen\n• Elevation if on limb\n• Apply heat after 24 hours\n\n**Prevention**:\n• Use insect repellent\n• Wear long sleeves in evening\n• Avoid bright colors outdoors\n• Keep mosquito nets clean\n• Avoid stagnant water\n\n**When to seek help**:\n• Severe swelling (larger than 10cm)\n• Multiple stings\n• Sting in mouth or throat\n• Signs of infection\n• Allergic reaction (difficulty breathing, severe swelling)\n• CALL 112 for allergic reaction\n\n**Recovery**:\nMost bites heal in 1-2 weeks",
      hi_IN: "कीट काटने और डंक का प्रबंधन:\n\n**तुरंत**:\n1. **डंक निकालें** (अगर मधुमक्खी):\n   • सपाट कोण से खरोंचें\n   • निचोड़ें नहीं\n2. **साफ करें** - साबुन और पानी\n3. **बर्फ लगाएं** - 10-15 मिनट\n4. **खुजली कम करें**:\n   • क्रीम लगाएं\n   • एंटीहिस्टामाइन टैबलेट\n   • कैलामाइन लोशन\n5. **न खरोंचें** - संक्रमण होगा\n\n**दर्द और सूजन**:\n• दर्द की दवा लें\n\n**रोकथाम**:\n• कीटनाशक लगाएं\n• लंबे कपड़े पहनें\n• मच्छर जाली साफ रखें\n\n**डॉक्टर के पास कब जाएं**:\n• गंभीर सूजन\n• कई डंक\n• संक्रमण के संकेत\n• सांस की कमी (एलर्जी)"
    }
  },
  electric_shock: {
    symptoms: ["electric shock", "electrocution", "electrical", "shock"],
    advice: {
      en_IN: "**ELECTRIC SHOCK - EMERGENCY FIRST AID**\n\n⚠️ **CALL 108 IMMEDIATELY!**\n\n**DO NOT touch person if still in contact with live wire!**\n\n**Immediate Actions**:\n1. **Turn off power** - If safe to do so\n2. **If can't turn off, use non-conductive object**:\n   • Wooden stick or broom\n   • Rubber gloves\n   • Plastic\n   • Push person away from source\n3. **Once separated**:\n   • Check for breathing and pulse\n   • Place in recovery position\n   • Check for burns (entry and exit points)\n4. **Monitor vitals**:\n   • Be ready to perform CPR\n   • Watch for heart arrhythmia\n   • Monitor consciousness\n5. **Keep warm** - Cover with blanket\n6. **Don't move unnecessarily** - Spinal injury possible\n7. **Wait for ambulance** - Serious internal damage possible\n\n**Burns from electric shock**:\n• May not be visible\n• Internal damage likely\n• Hospital examination essential\n• Can have complications hours later\n\n**CPR - If no breathing/pulse**:\n• Start chest compressions immediately\n• 100-120 compressions per minute\n• Continue until ambulance arrives\n\n**Prevention**:\n• Avoid using electrical appliances in wet areas\n• Don't use damaged cords\n• Keep water away from electricity\n• Use surge protectors\n• Have qualified electrician check home\n\n**Medical follow-up essential** - Even mild electric shocks can cause cardiac arrhythmias",
      hi_IN: "**विद्युत आघात - आपातकालीन चिकित्सा**\n\n⚠️ **तुरंत 108 कॉल करें!**\n\n**जीवित तार में छूने वाले व्यक्ति को न छुएं!**\n\n**तुरंत करें**:\n1. **बिजली बंद करें** - अगर सुरक्षित हो\n2. **अगर नहीं तो गैर-चालक वस्तु से दूर करें**:\n   • लकड़ी की छड़ी\n   • रबर के दस्ताने\n   • प्लास्टिक\n3. **अलग होने पर**:\n   • सांस/नाड़ी देखें\n   • बगल में रखें\n   • जलने के निशान देखें\n4. **सांस न हो तो**:\n   • CPR दें\n   • 100-120 बार/मिनट दबाएं\n5. **गर्म रखें** - कंबल से ढकें\n6. **एम्बुलेंस की प्रतीक्षा करें**\n\n**रोकथाम**:\n• गीले स्थान पर बिजली का सामान न लगाएं\n• क्षतिग्रस्त तार न लगाएं\n• विद्युत से पानी दूर रखें"
    }
  },
  earthquake: {
    symptoms: ["earthquake", "ground shaking", "tremor", "seismic"],
    advice: {
      en_IN: "**EARTHQUAKE SURVIVAL GUIDE**\n\n**DURING Earthquake**:\n1. **Drop, Cover, Hold On**:\n   • **DROP** immediately to hands and knees\n   • **COVER** head and neck with arms\n   • **HOLD** under sturdy table/desk\n2. **If indoors**:\n   • Stay inside (DON'T run outside)\n   • Get under desk/table away from windows\n   • Stay against interior wall\n   • Avoid windows, mirrors, heavy objects\n3. **If outdoors**:\n   • Move away from buildings\n   • Stay in open space\n   • Avoid trees and power lines\n4. **If in car**:\n   • Stay in car\n   • Move away from buildings\n   • Avoid overpasses, power lines\n   • Drive slowly to safe area\n5. **If in bed**:\n   • Stay in bed\n   • Cover head with pillow\n   • Avoid moving around\n\n**AFTER Earthquake**:\n1. **Check for injuries** - First aid if needed\n2. **Inspect building**:\n   • Check for gas leaks (smell)\n   • Check for electrical damage\n   • Look for structural damage\n3. **Aftershocks may occur** - Be prepared\n4. **Listen to news** for updates\n5. **Help others** - But stay safe\n\n**Emergency kit essentials**:\n• Water (1 liter per person per day)\n• Non-perishable food\n• First aid kit\n• Flashlight and batteries\n• Radio\n• Medications\n• Important documents\n• Cash\n\n**Home safety**:\n• Secure heavy furniture to walls\n• Store breakables low\n• Know how to turn off gas/electricity\n• Practice 'Drop, Cover, Hold On'",
      hi_IN: "**भूकंप से बचाव गाइड**\n\n**भूकंप के दौरान**:\n1. **ड्रॉप, कवर, होल्ड करें**:\n   • **गिर जाएं** - हाथ और घुटने पर\n   • **ढकें** - सिर और गर्दन को बाहों से\n   • **पकड़ें** - मेज/डेस्क के नीचे\n2. **अंदर होने पर**:\n   • अंदर रहें (बाहर न दौड़ें)\n   • मेज के नीचे जाएं\n   • खिड़कियों से दूर रहें\n3. **बाहर होने पर**:\n   • इमारतों से दूर जाएं\n   • खुली जगह पर रहें\n   • पेड़/बिजली लाइन से दूर\n4. **कार में होने पर**:\n   • कार में रहें\n   • इमारतों से दूर जाएं\n5. **बिस्तर में होने पर**:\n   • बिस्तर में रहें\n   • तकिए से सिर ढकें\n\n**भूकंप के बाद**:\n1. **चोटें देखें** - प्राथमिक चिकित्सा करें\n2. **इमारत की जांच करें**:\n   • गैस लीक देखें\n   • विद्युत क्षति देखें\n3. **आफ्टरशॉक** - सतर्क रहें\n4. **समाचार सुनें**\n5. **दूसरों की मदद करें**\n\n**आपातकालीन किट**:\n• पानी (हर व्यक्ति प्रति दिन 1 लीटर)\n• खराब न होने वाला खाना\n• प्राथमिक चिकित्सा किट\n• टॉर्च और बैटरी\n• रेडियो\n• दवाएं"
    }
  },
  flood: {
    symptoms: ["flood", "flooding", "water", "heavy rain", "submersion"],
    advice: {
      en_IN: "**FLOOD SAFETY GUIDE**\n\n**BEFORE Flood**:\n1. **Prepare emergency kit**:\n   • Drinking water and food\n   • First aid kit\n   • Medications and medical records\n   • Important documents (waterproof container)\n   • Flashlight and batteries\n   • Battery-powered radio\n   • Cash (ATMs may not work)\n2. **Know evacuation routes**\n3. **Store important items high**\n4. **Keep vehicles fueled**\n\n**DURING Flood**:\n1. **If told to evacuate - GO IMMEDIATELY**\n2. **If outdoors**:\n   • Never cross flooded roads (water only 2 feet deep can sweep away car)\n   • Never swim or wade in floodwater\n   • Avoid touching downed power lines\n   • Stay on higher ground\n3. **If indoors**:\n   • Go to higher floors immediately\n   • Don't use elevators\n   • Listen to emergency broadcasts\n   • Stay away from windows\n4. **Never**:\n   • Drive through flooded areas\n   • Walk through flowing water\n   • Touch contaminated water\n\n**AFTER Flood**:\n1. **Return home only when authorities say it's safe**\n2. **Check for injuries** - Seek medical help\n3. **Inspect home**:\n   • Check structural damage\n   • Look for gas leaks\n   • Check electrical damage\n   • Document damage (photos) for insurance\n4. **Water safety**:\n   • Boil water before drinking\n   • Wash hands frequently\n   • Sanitize surfaces\n   • Avoid contaminated water\n5. **Clean and disinfect**:\n   • Remove mud and debris\n   • Use bleach solution (1:10 ratio)\n   • Air out home\n\n**Common injuries in floods**:\n• Cuts from debris\n• Bacterial infections from contaminated water\n• Drowning risk",
      hi_IN: "**बाढ़ सुरक्षा गाइड**\n\n**बाढ़ से पहले**:\n1. **आपातकालीन किट तैयार करें**:\n   • पानी और खाना\n   • प्राथमिक चिकित्सा किट\n   • दवाएं\n   • महत्वपूर्ण दस्तावेज\n   • टॉर्च और बैटरी\n   • रेडियो\n2. **निकासी रूट जानें**\n3. **महत्वपूर्ण चीजें ऊपर रखें**\n\n**बाढ़ के दौरान**:\n1. **अगर निकासी का आदेश हो - तुरंत जाएं**\n2. **बाहर होने पर**:\n   • बाढ़ से भरी सड़क न पार करें\n   • पानी में न तैरें\n   • बिजली की लाइन न छुएं\n3. **अंदर होने पर**:\n   • ऊपरी मंजिल पर जाएं\n   • लिफ्ट न लें\n   • समाचार सुनें\n4. **कभी न करें**:\n   • बाढ़ से भरी जगह ड्राइव न करें\n   • पानी में न चलें\n   • दूषित पानी को न छुएं\n\n**बाढ़ के बाद**:\n1. **सुरक्षित होने के बाद ही घर जाएं**\n2. **चोटें देखें**\n3. **घर की जांच करें**:\n   • क्षति देखें\n   • गैस लीक देखें\n   • फोटो लें (बीमा के लिए)\n4. **पानी सुरक्षा**:\n   • उबाल कर पिएं\n   • हाथ धोएं\n   • सतह कीटाणुरहित करें\n5. **साफ करें** - ब्लीच से"
    }
  },
  cyclone: {
    symptoms: ["cyclone", "hurricane", "typhoon", "storm", "severe wind"],
    advice: {
      en_IN: "**CYCLONE/HURRICANE/TYPHOON SAFETY**\n\n**BEFORE Cyclone**:\n1. **Prepare emergency kit**:\n   • Food, water, medications\n   • First aid kit\n   • Flashlight, batteries, radio\n   • Important documents\n   • Cash and cards\n2. **Secure home**:\n   • Board up windows\n   • Secure loose objects (roofing, signs)\n   • Trim tree branches\n   • Clean gutters\n   • Stock firewood/fuel\n3. **Know evacuation routes**\n4. **Fill bathtub with water** (for drinking/flushing)\n5. **Charge all devices**\n\n**DURING Cyclone**:\n1. **If told to evacuate - GO IMMEDIATELY**\n2. **Stay indoors**:\n   • Go to interior room on lowest floor\n   • Away from windows and doors\n   • Bathrooms and closets are safest\n   • Avoid kitchens (utilities)\n3. **If outside** (before arrival):\n   • Get to shelter immediately\n   • Don't try to secure property\n   • Avoid mobile homes\n4. **Never**:\n   • Go outside during apparent calm (eye of storm)\n   • Try to drive\n   • Look out windows\n   • Use candles (fire risk)\n\n**AFTER Cyclone**:\n1. **Stay indoors** - Assess damage first\n2. **Watch for hazards**:\n   • Downed power lines\n   • Debris\n   • Falling branches\n   • Damaged structures\n3. **Provide first aid** - See emergency numbers\n4. **Clean up carefully**:\n   • Remove debris\n   • Document damage (photos)\n   • Contact insurance\n5. **Boil water** - May be contaminated\n6. **Listen to authorities** - For all-clear signal\n\n**Natural warning signs**:\n• Unusual wind changes\n• Rapid pressure drop\n• Unusually high tides\n• Unusual cloud formations",
      hi_IN: "**चक्रवात/तूफान सुरक्षा**\n\n**चक्रवात से पहले**:\n1. **आपातकालीन किट तैयार करें**:\n   • खाना, पानी, दवाएं\n   • प्राथमिक चिकित्सा किट\n   • टॉर्च, बैटरी, रेडियो\n2. **घर सुरक्षित करें**:\n   • खिड़कियां बोर्ड करें\n   • ढीली चीजें सुरक्षित करें\n   • पेड़ की शाखाएं काटें\n   • नालियां साफ करें\n3. **निकासी रूट जानें**\n4. **बाथटब पानी से भरें**\n5. **सभी डिवाइस चार्ज करें**\n\n**चक्रवात के दौरान**:\n1. **निकासी का आदेश हो - तुरंत जाएं**\n2. **अंदर रहें**:\n   • अंदर का कमरा\n   • खिड़कियों से दूर\n   • बाथरूम सबसे सुरक्षित\n3. **बाहर होने पर** (आने से पहले):\n   • तुरंत आश्रय लें\n4. **कभी न करें**:\n   • आँख (शांत क्षेत्र) के दौरान बाहर न जाएं\n   • ड्राइव न करें\n   • खिड़कियों से न देखें\n\n**चक्रवात के बाद**:\n1. **अंदर रहें** - क्षति मूल्यांकन करें\n2. **खतरे देखें**:\n   • बिजली की लाइन\n   • मलबा\n   • गिरती शाखाएं\n3. **पहली सहायता दें**\n4. **सफाई करें** - क्षति दस्तावेज करें\n5. **पानी उबालें** - दूषित हो सकता है"
    }
  },
};

export function getMedicalAdvice(userMessage: string, language: string = 'en_IN'): { type: string; advice: string } | null {
  const lowerMessage = userMessage.toLowerCase();

  for (const [conditionKey, conditionData] of Object.entries(MEDICAL_ADVICE)) {
    const symptoms = (conditionData as any).symptoms || [];
    if (symptoms.some((symptom: string) => lowerMessage.includes(symptom))) {
      const advice = (conditionData as any).advice[language] || (conditionData as any).advice['en_IN'];
      return {
        type: conditionKey,
        advice: advice
      };
    }
  }

  return null;
}
